// <auto-generated />
using System;
using Investment.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Investment.Infrastructure.Migrations
{
    [DbContext(typeof(InvestmentDbContext))]
    [Migration("20260121132543_modify_Contract_addRelation")]
    partial class modify_Contract_addRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("integer");

                    b.Property<int>("MinAmount")
                        .HasColumnType("integer");

                    b.Property<short>("MinDurationOfDay")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Rate")
                        .HasPrecision(28, 2)
                        .HasColumnType("numeric(28,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.ContractMarketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rate")
                        .HasPrecision(28, 2)
                        .HasColumnType("numeric(28,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ContractMarketTypes");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.UserContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 2)
                        .HasColumnType("numeric(28,2)");

                    b.Property<int>("ContractDurationType")
                        .HasMaxLength(1000)
                        .HasColumnType("integer");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int>("ContractMarketTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DurationOfDay")
                        .HasMaxLength(4000)
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasMaxLength(1000)
                        .HasColumnType("integer");

                    b.Property<decimal>("SumRate")
                        .HasPrecision(28, 2)
                        .HasColumnType("numeric(28,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ContractMarketTypeId");

                    b.ToTable("UserContracts");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.UserContractLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasMaxLength(1000)
                        .HasColumnType("integer");

                    b.Property<int>("UserContractId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserContractId");

                    b.ToTable("UserContractLogs");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.UserContractProfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeposit")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rate")
                        .HasPrecision(28, 2)
                        .HasColumnType("numeric(28,2)");

                    b.Property<int>("UserContractId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserContractId");

                    b.ToTable("UserContractProfits");
                });

            modelBuilder.Entity("Investment.Domain.Transactions.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 2)
                        .HasColumnType("numeric(28,2)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ReasonType")
                        .HasMaxLength(3)
                        .HasColumnType("integer");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TransactionType")
                        .HasMaxLength(3)
                        .HasColumnType("integer");

                    b.Property<int>("UserBalanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserBalanceId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Investment.Domain.Transactions.Entities.UserBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 2)
                        .HasColumnType("numeric(28,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserBalances");
                });

            modelBuilder.Entity("Investment.Domain.Users.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(130)
                        .IsUnicode(false)
                        .HasColumnType("character varying(130)");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("integer");

                    b.Property<int?>("RevokeReason")
                        .HasColumnType("integer");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("ReplacedByTokenId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Investment.Domain.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Investment.Domain.Users.Entities.ValidationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasMaxLength(130)
                        .IsUnicode(false)
                        .HasColumnType("character varying(130)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ValidationTokenType")
                        .HasMaxLength(2)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HashedToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ValidationTokens");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.UserContract", b =>
                {
                    b.HasOne("Investment.Domain.Contracts.Entities.Contract", "Contract")
                        .WithMany("UserContracts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investment.Domain.Contracts.Entities.ContractMarketType", "ContractMarketType")
                        .WithMany()
                        .HasForeignKey("ContractMarketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("ContractMarketType");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.UserContractLog", b =>
                {
                    b.HasOne("Investment.Domain.Contracts.Entities.UserContract", "UserContract")
                        .WithMany("UserContractLogs")
                        .HasForeignKey("UserContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserContract");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.UserContractProfit", b =>
                {
                    b.HasOne("Investment.Domain.Contracts.Entities.UserContract", null)
                        .WithMany("userContractProfits")
                        .HasForeignKey("UserContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Investment.Domain.Transactions.Entities.Transaction", b =>
                {
                    b.HasOne("Investment.Domain.Transactions.Entities.UserBalance", "UserBalance")
                        .WithMany("Transactions")
                        .HasForeignKey("UserBalanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserBalance");
                });

            modelBuilder.Entity("Investment.Domain.Users.Entities.RefreshToken", b =>
                {
                    b.HasOne("Investment.Domain.Users.Entities.RefreshToken", "ReplacedByToken")
                        .WithOne()
                        .HasForeignKey("Investment.Domain.Users.Entities.RefreshToken", "ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Investment.Domain.Users.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Investment.Domain.Users.Entities.ValidationToken", b =>
                {
                    b.HasOne("Investment.Domain.Users.Entities.User", "User")
                        .WithMany("ValidationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.Contract", b =>
                {
                    b.Navigation("UserContracts");
                });

            modelBuilder.Entity("Investment.Domain.Contracts.Entities.UserContract", b =>
                {
                    b.Navigation("UserContractLogs");

                    b.Navigation("userContractProfits");
                });

            modelBuilder.Entity("Investment.Domain.Transactions.Entities.UserBalance", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Investment.Domain.Users.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ValidationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
